# Sujet Trottinettes 

### Mohamed Benyahia

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy

##### Valeurs numériques des paramètres:

In [2]:
N=100# Nombre total de trottinettes
lambda_ = 0.1 # min^(-1) taux d'emprunt moyen
t_trajet=5 # min
p_panne=0.01 # probabilité pour une trottinette de tomber en panne
p_vide=0.1 # probabilité pour une trottinette d'avoir sa batterie vide lorsqu’elle est utilisée.
t_intervention=30 # min le temps moyen d’intervention d’un prestataire ou d’un technicien
t_recharge=240 #min le temps moyen de recharge de la batterie d’une trottinette
t_reparation=720 #min le temps moyen de réparation pour une trottinette. 



#### 1.

Espace d'états : $E=\{ (n_{non\ utilisée},n_{utilisée},n_{vide},n_{panne}) /n_{utilisée}+n_{non\ utilisée}+n_{vide}+n_{panne}=N\}$  
Diagramme de transitions: (Sachant qu'on suppose qu’une trottinette non utilisée ne peut pas tomber en panne ou avoir une batterie vide.)   

![Diagramm](diagramme.png)

 
$ q(n, T_{non\ utilisée \rightarrow utilisée})= \phi_{non\ utilisée}(n_{non\ utilisée})\  \lambda_{non\ utilisée \rightarrow utilisée}$  
$ q(n, T_{utilisée \rightarrow non\ utilisée })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow non\ utilisée}$  
$ q(n, T_{utilisée \rightarrow panne })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow panne}$  
$ q(n, T_{utilisée \rightarrow vide })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow vide}$  
$q(n, T_{panne \rightarrow non\ utilisée })= \phi_{panne }(n_{panne})\  \lambda_{panne \rightarrow non\ utilisée}$    
$q(n, T_{vide \rightarrow non\ utilisée })= \phi_{vide }(n_{vide})\  \lambda_{vide \rightarrow non\ utilisée}$ 

#### 2.  

On considère qu’il y a suffisamment de prestataires et de techniciens pour chercher, charger et réparer les trottinettes qui en ont besoin simultanément

$ q(n, T_{non\ utilisée \rightarrow utilisée})= \phi_{non\ utilisée}(n_{non\ utilisée})\  \lambda_{non\ utilisée \rightarrow utilisée}= \mathbb{1}_{n_{non\ utilisée}>0} \ \lambda$  
$ q(n, T_{utilisée \rightarrow non\ utilisée })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow non\ utilisée}= n_{utilisée } \ \frac{1}{t_{trajet}}\ (1-p_{panne}-p_{vide})$   
$ q(n, T_{utilisée \rightarrow panne })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow panne}=\ n_{utilisée } \frac{1}{t_{trajet}} \ p_{panne} $  
$ q(n, T_{utilisée \rightarrow vide })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow vide}=
 n_{utilisée }\ \frac{1}{t_{trajet}} \  p_{vide}$   
$q(n, T_{panne \rightarrow non\ utilisée })= \phi_{panne }(n_{panne})\  \lambda_{panne \rightarrow non\ utilisée}=n_{panne} \ \frac{1}{t_{intervention}+t_{reparation}} $   
$q(n, T_{vide \rightarrow non\ utilisée })= \phi_{vide }(n_{vide})\  \lambda_{vide \rightarrow non\ utilisée}=n_{vide} \ \frac{1}{t_{intervention}+t_{recharge}}$   

#### 3.

##### On attribue à chaque colonie un indice : Non Utilisée:0  Utilisée:1  Vide:2  Panne:3

##### Proba stationnaire:  
$\pi(n_{non\ utilisée},n_{utilisée},n_{vide},n_{panne})=\frac{1}{K}  \frac{\alpha_{non\ utilisée}^{n_{non\ utilisée}}}{1} \ \frac{\alpha_{utilisée}^{n_{utilisée}}}{n_{utilisée}!} \frac{\alpha_{vide}^{n_{vide}}}{{n_{vide}}!} \frac{\alpha_{panne}^{n_{panne}}}{{n_{panne}}!} =\frac{1}{K} \ \frac{\alpha_{0}^{n_{0}}}{1} \frac{\alpha_{1}^{n_{1}}}{n_{1}!}  \frac{\alpha_{2}^{n_{2}}}{{n_{2}}!} \frac{\alpha_{3}^{n_{3}}}{{n_{3}}!}$  
Equations de traffic:  $\alpha_j \sum_{k=0 \ k\neq j }^{3} \lambda_{j\ k} = \sum_{k=0 \ k\neq j}^{3} \alpha_k \lambda_{k\ j} \ pour \ j=0,1,2,3 $  
pour j=0 on trouve : $\alpha_{0} \ \lambda_{0\ 1} = \alpha_{1} \ \lambda_{1\ 0} + \alpha_{2} \ \lambda_{2\ 0} + \alpha_{3} \ \lambda_{3\ 0} $  
pour j=1 on trouve : $\alpha_{0} \ \lambda_{0\ 1} = \alpha_{1} (\lambda_{1\ 0} +  \lambda_{1\ 2} + \lambda_{1\ 3}) $  
pour j=2 on trouve : $\alpha_{2} \ \lambda_{2\ 0} = \alpha_{1} \lambda_{1\ 2}$    
pour j=3 on trouve: $\alpha_{3} \ \lambda_{3\ 0} = \alpha_{1} \lambda_{1\ 3}$   
On trouve donc que $\alpha_{1}  = \alpha_{0} \ \frac{\lambda_{0\ 1}}{\lambda_{1\ 0} +  \lambda_{1\ 2} + \lambda_{1\ 3}}$  
et  $\alpha_{2}  = \alpha_{0} \ \frac{\lambda_{1\ 2} \lambda_{0\ 1}}{\lambda_{2\ 0}(\lambda_{1\ 0} +  \lambda_{1\ 2} + \lambda_{1\ 3})}$    
et $\alpha_{3}  = \alpha_{0} \ \frac{\lambda_{1\ 3} \lambda_{3\ 0}}{\lambda_{3\ 0}(\lambda_{1\ 0} +  \lambda_{1\ 2} + \lambda_{1\ 3})}$  

#### 4.

Construisons d'abord une fonction qui permet de retourner le générateur infinitésimal:

In [3]:

#Construction du generateur infinitesimal

def generateA(n):
    A=np.zeros((4,4))
    if n[0]>0:
        A[0][1]=lambda_
        A[0][0]=-A[0][1]
    if n[1]>0:

        A[1][1]=-n[1]*1/t_trajet
        A[1][0]=n[1]*(1-p_panne-p_vide)/t_trajet
        A[1][2]=n[1]*p_vide/t_trajet
        A[1][3]=n[1]*p_panne/t_trajet
    if n[2]>0:
        A[2][0]=n[2]*1/(t_intervention+t_recharge)
        A[2][2]=-A[2][0]
    if n[3]>0:

        A[3][0]=n[3]*1/(t_reparation+t_intervention)
        A[3][3]=-A[3][0]

    return A



La fonction ci-dessous permet de simuler une variable aléatoire X suivant une loi $\nu$ qui prend en entrée p_cumul avec $p_{cumul}(0)=\nu(0)$ et $p_{cumul}(n)=\sum_{i=0}^{n}\nu(i)$

In [4]:

def simulerVarAleat(p_cumul):
    x=np.random.uniform(0,1)
    n=0
    while x>p_cumul[n]:
        
        n=n+1
    return n

La fonction ci-dessous permet de simuler les trajectoires du modèle sur un temps t_max. A chaque fois, on sélectionne la colonie de départ x qui a la valeur de la réalisation de la loi exponentielle correspondante au  temps de sejour la plus faible parmi toutes les colonies. Ensuite, on ajoute au compteur du temps cette valeur. Puis on sélectionne la colonie d'arrivée y en simulant une variable aleatoire qui suit la loi de transition a partir de la colonie x. Enfin, on décrémente le nombre d'individus de la colonie x et on incrémente le nombre d'individus de la colonie y. 

In [5]:
def simulerTrajectoire(N,t_max=100*60):
    
    
    t=0

    #tirer une configuration initiale
    n=np.array([N,0,0,0])
    

    while t<=t_max:
        #Pour choisir la colonie de depart x, on prend celle qui a la valeur la plus faible de la realisation 
        #de la loi exponentielle correspondante au temps de sejour dans cette colonie
        #cette valeur est ensuite ajoutee au temps
        A=generateA(n)
        temps_array=np.array([-1/(-A[x][x])*np.log(np.random.uniform(0,1)) if n[x]>0 else np.inf for x in range(4) ])
        x=np.argmin(temps_array)

        temps=temps_array[x]
        
        t=t+temps
        
        
        #pour choisir la colonie d'arrivee y, on simule une variable aleatoire qui suit la loi de transition
        #depuis la colonie x
        p_x_y=np.array([A[x][y]/np.abs(A[x][x]) if y!=x else 0 for y in range(4)])
        
        p_cumul=p_x_y
        for k in range(1,4):
            p_cumul[k]=p_cumul[k-1]+p_x_y[k]
        
        y=simulerVarAleat(p_cumul)
        print(t,n)
        #Enfin on decremente le nombre d'individus de la colonie x
        #et on incremente le nombre d'individus de la colonie y

        n[x]=n[x]-1
        n[y]=n[y]+1
        
    
    
    
    


In [6]:
tm=100*60 #100h=100*60min
simulerTrajectoire(N=100,t_max=tm)



1.3897567862649334 [100   0   0   0]
3.1068085536371983 [99  1  0  0]
9.70567239938212 [100   0   0   0]
13.696024630798973 [99  1  0  0]
26.52660331826437 [99  0  1  0]
30.636899597236205 [98  1  1  0]
46.48070667844709 [99  0  1  0]
47.43230831063606 [98  1  1  0]
48.82577356105013 [99  0  1  0]
49.53331550476279 [98  1  1  0]
52.00934434089643 [97  2  1  0]
52.489239599491505 [98  1  1  0]
54.28569149646269 [97  2  1  0]
65.60572391993827 [98  1  1  0]
73.51493619004891 [98  0  1  1]
80.09839694449862 [97  1  1  1]
82.32142513574348 [98  0  1  1]
84.12628986142636 [97  1  1  1]
86.15116475555496 [98  0  1  1]
86.95142437227652 [97  1  1  1]
95.7092604599037 [98  0  1  1]
96.17284890034843 [97  1  1  1]
96.6250314479468 [97  0  2  1]
102.51942422914041 [96  1  2  1]
110.69668734197283 [97  0  2  1]
113.66195225650266 [96  1  2  1]
119.22122578726128 [97  1  1  1]
124.54303018883206 [98  0  1  1]
125.94673800842773 [97  1  1  1]
131.44142682880354 [98  0  1  1]
132.04509851686709 [97 

#### 5.

$\pi(n_{non\ utilisée},n_{utilisée},n_{vide},n_{panne})=\frac{1}{K} \ \frac{\alpha_{0}^{n_{0}}}{1} \frac{\alpha_{1}^{n_{1}}}{n_{1}!}  \frac{\alpha_{2}^{n_{2}}}{n_{2}!} \frac{\alpha_{3}^{n_{3}}}{n_{3}!}$  
$\alpha_{1}  = \alpha_{0} \ \frac{\lambda_{0\ 1}}{\lambda_{1\ 0} +  \lambda_{1\ 2} + \lambda_{1\ 3}}\ et\    \alpha_{2}  = \alpha_{0} \frac{\lambda_{1\ 2} \lambda_{0\ 1}}{\lambda_{2\ 0}(\lambda_{1\ 0} +  \lambda_{1\ 2} + \lambda_{1\ 3})}\ et\    \alpha_{3}  = \alpha_{0} \ \frac{\lambda_{1\ 3} \lambda_{0\ 1}}{\lambda_{3\ 0}(\lambda_{1\ 0} +  \lambda_{1\ 2} + \lambda_{1\ 3})}$   
$\sum \pi(n_{non\ utilisée},n_{utilisée},n_{vide},n_{panne}) = 1$

In [7]:
def probaStationnaire(n,alpha,K):
    p=1/(K*int(np.math.factorial(n[1]))*int(np.math.factorial(n[2]))*int(np.math.factorial(n[3])))
    for i in range(4):
        p=p*alpha[i]**n[i]
    return p

#On liste toutes les configurations possibles de notre systeme 
configurations=[]

for i in range(4):
    configuration=np.zeros(4,dtype='int')
    configuration[i]=2
    configurations.append(configuration)
    for j in range(i+1,4):
        configuration=np.zeros(4,dtype='int')
        configuration[i]=1
        configuration[j]=1
        configurations.append(configuration)
        
        
            



def calculAlphas(alpha0):
    lambda_01=lambda_
    lambda_10=(1-p_panne-p_vide)/t_trajet
    lambda_12=p_vide/t_trajet
    lambda_13=p_panne/t_trajet
    lambda_20=1/(t_intervention+t_recharge)
    lambda_30=1/(t_reparation+t_intervention)
    alpha1=alpha0*lambda_01/(lambda_10+lambda_12+lambda_13)
    alpha2=alpha0*lambda_01*lambda_12/(lambda_20*(lambda_10+lambda_12+lambda_13))
    alpha3=alpha0*lambda_01*lambda_13/(lambda_30*(lambda_10+lambda_12+lambda_13))
    return np.array([alpha0,alpha1,alpha2,alpha3])

alpha0=1
alpha=calculAlphas(alpha0)



#On calcule la constante de normalisation K.
K=1

    
D_prob={}#Dictionnaire qui fait correspondre a chaque numero de configuration
#la valeur de probabilite stationnaire correspondante
D_config={}#Dictionnaire qui fait correspondre a chaque configuration (valeur) un numero (cle) entre 0 et 9.
s=0
i=0
for n in configurations:
    s+=probaStationnaire(n,alpha,K)
    D_prob[i]=probaStationnaire(n,alpha,K)
    D_config[i]=n
    i=i+1
K=s

s=0
i=0
for n in configurations:
    s+=probaStationnaire(n,alpha,K)
    D_prob[i]=probaStationnaire(n,alpha,K)
    D_config[i]=n
    i=i+1
        
print(s)





1.0


In [8]:
print(D_prob)
print(D_config)
for k in list(D_config.keys()):
    print(D_config[k])

{0: 0.07842368395255367, 1: 0.03921184197627684, 2: 0.21174394667189492, 3: 0.05881776296441526, 4: 0.009802960494069214, 5: 0.10587197333594747, 6: 0.029408881482207636, 7: 0.2858543280070582, 8: 0.15880796000392122, 9: 0.022056661111655728}
{0: array([2, 0, 0, 0]), 1: array([1, 1, 0, 0]), 2: array([1, 0, 1, 0]), 3: array([1, 0, 0, 1]), 4: array([0, 2, 0, 0]), 5: array([0, 1, 1, 0]), 6: array([0, 1, 0, 1]), 7: array([0, 0, 2, 0]), 8: array([0, 0, 1, 1]), 9: array([0, 0, 0, 2])}
[2 0 0 0]
[1 1 0 0]
[1 0 1 0]
[1 0 0 1]
[0 2 0 0]
[0 1 1 0]
[0 1 0 1]
[0 0 2 0]
[0 0 1 1]
[0 0 0 2]


On garde le meme code que la fonction qu'on a utilisée avant pour simuler les trajectoires. La seule modification c'est que la fonction stocke a chaque fois le temps passe dans une configuration dans un dictionnaire. A la fin, on prend comme valeur de la probabilité stationnaire le rapport du temps cumulé  sur t_max.

In [9]:
def simulerTraj_CalculProb(N,t_max=100*60):
    
    
    t=0

    
    n=np.array([N,0,0,0])
    #On initialise notre dictionnaire
    D_sim={ i:0 for i in range(10)}
    

    while t<=t_max:
        A=generateA(n)
        temps_array=np.array([-1/(-A[x][x])*np.log(np.random.uniform(0,1)) if n[x]>0 else np.inf for x in range(4) ])
        x=np.argmin(temps_array)

        temps=temps_array[x]
        
        t=t+temps
        
        
        p_x_y=np.array([A[x][y]/np.abs(A[x][x]) if y!=x else 0 for y in range(4)])
        
        p_cumul=p_x_y
        for k in range(1,4):
            p_cumul[k]=p_cumul[k-1]+p_x_y[k]
        
        y=simulerVarAleat(p_cumul)
        #on ajoute le temps passe dans l'etat n a la valeur de la cle 
        #qui est le numero de la configuration correspondante
        ind=[i for i in D_config if np.array_equal(D_config[i],n)]
      
        D_sim[ind[0]]+=temps
        n[x]=n[x]-1
        n[y]=n[y]+1
    return D_sim
        

##### 1 ère manière: Simuler sur un temps très long

In [10]:
tm=50000*60
D_sim=simulerTraj_CalculProb(N=2,t_max=tm)
D1={i:D_sim[i]/tm for i in range(10)}
print(D1)

print(sum(list(D_sim.values()))/tm)

{0: 0.08126673124067335, 1: 0.040769072462846674, 2: 0.21246558959665313, 3: 0.05728000554350881, 4: 0.010238951442959093, 5: 0.10552499280142559, 6: 0.028825092462100684, 7: 0.2927137538635657, 8: 0.1522511386347993, 9: 0.01870129242726552}
1.000036620475798


2 ème manière: moyenner le résultat de plusieurs simulations sur un temps plus court

In [11]:
tm=100*60
D2={i:0 for i in range(10)}
n_iter=500
for k in range(n_iter):
    D_sim=simulerTraj_CalculProb(N=2,t_max=tm)
    D2={i:D_sim[i]+D2[i] for i in range(10)}
D2={i:D2[i]/(n_iter*tm) for i in range(10)}
print(D2)

print(sum(list(D2.values())))

{0: 0.08968039276782598, 1: 0.04400547779496473, 2: 0.21121748386582423, 3: 0.05886409894800674, 4: 0.010883013215432995, 5: 0.10578623600438147, 6: 0.029472918885243643, 7: 0.28723461045299997, 8: 0.15775983640387445, 9: 0.02040783479250765}
1.015311903131062


In [12]:
print("Valeurs theoriques:")
print(D_prob)

Valeurs theoriques:
{0: 0.07842368395255367, 1: 0.03921184197627684, 2: 0.21174394667189492, 3: 0.05881776296441526, 4: 0.009802960494069214, 5: 0.10587197333594747, 6: 0.029408881482207636, 7: 0.2858543280070582, 8: 0.15880796000392122, 9: 0.022056661111655728}


##### Intervalles de confiance de niveau $1-\alpha$

In [13]:
from scipy.stats import t #Student distribution
Y=np.array(list(D_prob.values()))
Y_hat=np.array(list(D1.values()))
n=10
alpha=0.01
CI=[]
sigma_hat=np.sqrt(np.linalg.norm(Y-Y_hat)**2/(n-1))

for i in range(10):
    err_i=t.ppf(1-alpha/2,n-2)*sigma_hat/np.sqrt(n)
    CI_i=[Y_hat[i]-err_i,Y_hat[i]+err_i]
    CI.append(CI_i)
    print("Conf interval for stationary proba at configurat number ",i,CI_i,"theoretical result",Y[i])

Conf interval for stationary proba at configurat number  0 [0.07746812628978174, 0.08506533619156496] theoretical result 0.07842368395255367
Conf interval for stationary proba at configurat number  1 [0.03697046751195506, 0.04456767741373829] theoretical result 0.03921184197627684
Conf interval for stationary proba at configurat number  2 [0.20866698464576153, 0.21626419454754472] theoretical result 0.21174394667189492
Conf interval for stationary proba at configurat number  3 [0.0534814005926172, 0.06107861049440042] theoretical result 0.05881776296441526
Conf interval for stationary proba at configurat number  4 [0.006440346492067482, 0.014037556393850703] theoretical result 0.009802960494069214
Conf interval for stationary proba at configurat number  5 [0.10172638785053398, 0.1093235977523172] theoretical result 0.10587197333594747
Conf interval for stationary proba at configurat number  6 [0.025026487511209075, 0.03262369741299229] theoretical result 0.029408881482207636
Conf inter

On voit que presque toutes les valeurs theoriques de la probabilite stationnaire appartiennent aux intervalles de confiance des valeurs de la simulation. Donc elle est valide.

#### 6.

$ q(n, T_{non\ utilisée \rightarrow utilisée})= \phi_{non\ utilisée}(n_{non\ utilisée})\  \lambda_{non\ utilisée \rightarrow utilisée}= \mathbb{1}_{n_{non\ utilisée}>0} \ \lambda$  
$ q(n, T_{utilisée \rightarrow non\ utilisée })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow non\ utilisée}= n_{utilisée } \ \frac{1}{t_{trajet}}\ (1-p_{panne}-p_{vide})$   
$ q(n, T_{utilisée \rightarrow panne })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow panne}=\ n_{utilisée } \frac{1}{t_{trajet}} \ p_{panne} $  
$ q(n, T_{utilisée \rightarrow vide })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow vide}=
 n_{utilisée }\ \frac{1}{t_{trajet}} \  p_{vide}$     
 si $n_{panne}<=n_t$: $q(n, T_{panne \rightarrow non\ utilisée })= \phi_{panne }(n_{panne})\  \lambda_{panne \rightarrow non\ utilisée}=n_{panne} \ \frac{1}{t_{intervention}+t_{t_reparation}} $   

 sinon  $q(n, T_{panne \rightarrow non\ utilisée })= \phi_{panne }(n_{panne})\  \lambda_{panne \rightarrow non\ utilisée}=n_t \ \frac{1}{t_{intervention}+t_{t_reparation}} $

si $n_{vide}<=n_p$:$q(n, T_{vide \rightarrow non\ utilisée })= \phi_{vide }(n_{vide})\  \lambda_{vide \rightarrow non\ utilisée}=n_{vide} \ \frac{1}{t_{intervention}+t_{recharge}}$      

sinon  $q(n, T_{vide \rightarrow non\ utilisée })= \phi_{vide }(n_{vide})\  \lambda_{vide \rightarrow non\ utilisée}=n_p \ \frac{1}{t_{intervention}+t_{recharge}}$    
La nouvelle expression de la probabilite stationnaire :  

$\pi(n_{non\ utilisée},n_{utilisée},,n_{vide},n_{panne})=\frac{1}{K} \  \frac{\alpha_{non\ utilisée}^{n_{non\ utilisée}}}{1} \frac{\alpha_{utilisée}^{n_{utilisée}}}{n_{utilisée}!} \frac{\alpha_{vide}^{n_{vide}}}{{min(n_p,n_{vide})}!} \frac{\alpha_{panne}^{n_{panne}}}{{min(n_t,n_{panne})}!} =\frac{1}{K} \ \frac{\alpha_{0}^{n_{0}}}{1} \frac{\alpha_{1}^{n_{1}}}{n_{1}!}  \frac{\alpha_{2}^{n_{2}}}{{min(n_p,n_{2})}!} \frac{\alpha_{3}^{n_{3}}}{{min(n_t,n_{3})}!}$ 

#### 7.

Nouveau Espace d'états : $E=\{ (n_{non\ utilisée},n_{utilisée},n_{vide},n_{panne},n_{irréparable}) /n_{utilisée}+n_{non\ utilisée}+n_{vide}+n_{panne}+n_{irréparable}=N\}$   
![Diagramm](diagram.png)

$ q(n, T_{non\ utilisée \rightarrow utilisée})= \phi_{non\ utilisée}(n_{non\ utilisée})\  \lambda_{non\ utilisée \rightarrow utilisée}= \mathbb{1}_{n_{non\ utilisée}>0} \ \lambda$  
$ q(n, T_{utilisée \rightarrow non\ utilisée })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow non\ utilisée}= n_{utilisée } \ \frac{1}{t_{trajet}}\ (1-p_{panne}-p_{vide})$   
$ q(n, T_{utilisée \rightarrow panne })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow panne}=\ n_{utilisée } \frac{1}{t_{trajet}} \ p_{panne} $  
$ q(n, T_{utilisée \rightarrow vide })= \phi_{utilisée }(n_{utilisée })\  \lambda_{utilisée \rightarrow vide}=
 n_{utilisée }\ \frac{1}{t_{trajet}} \  p_{vide}$   
$q(n, T_{panne \rightarrow non\ utilisée })= \phi_{panne }(n_{panne})\  \lambda_{panne \rightarrow non\ utilisée}=n_{panne} \ (1-p_i) \ \frac{1}{t_{intervention}+t_{reparation}} $   
$q(n, T_{panne \rightarrow irréparable })= \phi_{panne }(n_{panne})\  \lambda_{panne \rightarrow non\ utilisée}=n_{panne} \ p_i\ \frac{1}{t_{intervention}+t_{reparation}} $  
$q(n, T_{vide \rightarrow non\ utilisée })= \phi_{vide }(n_{vide})\  \lambda_{vide \rightarrow non\ utilisée}=n_{vide} \ \frac{1}{t_{intervention}+t_{recharge}}$ 